<?php
return array (
  'ZC_CLOSE_WHOLE_SITE' => ,
  'ZC_DATABASE_TYPE' => '',
  'ZC_SQLITE_NAME' => '',
  'ZC_SQLITE_PRE' => '',
  'ZC_MYSQL_SERVER' => '',
  'ZC_MYSQL_USERNAME' => '',
  'ZC_MYSQL_PASSWORD' => '',
  'ZC_MYSQL_NAME' => '',
  'ZC_MYSQL_CHARSET' => '',
  'ZC_MYSQL_PRE' => '',
  'ZC_MYSQL_ENGINE' => '',
  'ZC_MYSQL_PORT' => '',
  'ZC_MYSQL_PERSISTENT' => ,
  'ZC_PGSQL_SERVER' => '',
  'ZC_PGSQL_USERNAME' => '',
  'ZC_PGSQL_PASSWORD' => '',
  'ZC_PGSQL_NAME' => '',
  'ZC_PGSQL_CHARSET' => '',
  'ZC_PGSQL_PRE' => '',
  'ZC_PGSQL_PORT' => '',
  'ZC_PGSQL_PERSISTENT' => ,
  'ZC_YUN_SITE' => '',
);
